#!/bin/bash

source_dir=$(pwd)
target_dir=$(dirname "$source_dir")  # Parent directory

# Copy HTML files from source to target directory
for file in ./*.html; do
  filename=$(basename "$file")
  cp "$file" "$target_dir/$filename"
done
